<?php

namespace ContainerZkRDcZs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnalyzeDocumentation_LazyService extends Dedoc_Scramble_Tests_KernelTestDebugContainer
{
    /**
     * Gets the private '.Dedoc\Scramble\Console\Commands\AnalyzeDocumentation.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.Dedoc\\Scramble\\Console\\Commands\\AnalyzeDocumentation.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('scramble:analyze', [], 'Analyzes the documentation generation process to surface any issues.', false, #[\Closure(name: 'Dedoc\\Scramble\\Console\\Commands\\AnalyzeDocumentation')] fn (): \Dedoc\Scramble\Console\Commands\AnalyzeDocumentation => ($container->privates['Dedoc\\Scramble\\Console\\Commands\\AnalyzeDocumentation'] ?? $container->load('getAnalyzeDocumentationService')));
    }
}
