<?php

namespace ContainerZkRDcZs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnalyzeDocumentationService extends Dedoc_Scramble_Tests_KernelTestDebugContainer
{
    /**
     * Gets the private 'Dedoc\Scramble\Console\Commands\AnalyzeDocumentation' shared autowired service.
     *
     * @return \Dedoc\Scramble\Console\Commands\AnalyzeDocumentation
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Console/Commands/AnalyzeDocumentation.php';

        $container->privates['Dedoc\\Scramble\\Console\\Commands\\AnalyzeDocumentation'] = $instance = new \Dedoc\Scramble\Console\Commands\AnalyzeDocumentation(($container->privates['Dedoc\\Scramble\\Generator'] ?? $container->load('getGeneratorService')), ($container->privates['Dedoc\\Scramble\\GeneratorConfig'] ?? $container->load('getGeneratorConfigService')));

        $instance->setName('scramble:analyze');
        $instance->setDescription('Analyzes the documentation generation process to surface any issues.');

        return $instance;
    }
}
