<?php

namespace ContainerZkRDcZs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContextReferencesCollectionService extends Dedoc_Scramble_Tests_KernelTestDebugContainer
{
    /**
     * Gets the private 'Dedoc\Scramble\ContextReferencesCollection' shared autowired service.
     *
     * @return \Dedoc\Scramble\ContextReferencesCollection
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/ContextReferencesCollection.php';

        return $container->privates['Dedoc\\Scramble\\ContextReferencesCollection'] = new \Dedoc\Scramble\ContextReferencesCollection();
    }
}
