<?php

namespace ContainerZkRDcZs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContextReferencesService extends Dedoc_Scramble_Tests_KernelTestDebugContainer
{
    /**
     * Gets the private 'Dedoc\Scramble\ContextReferences' shared autowired service.
     *
     * @return \Dedoc\Scramble\ContextReferences
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/ContextReferences.php';
        include_once \dirname(__DIR__, 4).'/src/ContextReferencesCollection.php';

        $a = ($container->privates['Dedoc\\Scramble\\ContextReferencesCollection'] ??= new \Dedoc\Scramble\ContextReferencesCollection());

        return $container->privates['Dedoc\\Scramble\\ContextReferences'] = new \Dedoc\Scramble\ContextReferences($a, $a, $a, $a, $a, $a, $a, $a, $a, $a);
    }
}
