<?php

namespace ContainerZkRDcZs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCleanupUnusedResponseReferencesTransformerService extends Dedoc_Scramble_Tests_KernelTestDebugContainer
{
    /**
     * Gets the private 'Dedoc\Scramble\DocumentTransformers\CleanupUnusedResponseReferencesTransformer' shared autowired service.
     *
     * @return \Dedoc\Scramble\DocumentTransformers\CleanupUnusedResponseReferencesTransformer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Contracts/DocumentTransformer.php';
        include_once \dirname(__DIR__, 4).'/src/DocumentTransformers/CleanupUnusedResponseReferencesTransformer.php';

        return $container->privates['Dedoc\\Scramble\\DocumentTransformers\\CleanupUnusedResponseReferencesTransformer'] = new \Dedoc\Scramble\DocumentTransformers\CleanupUnusedResponseReferencesTransformer();
    }
}
