<?php

namespace ContainerZkRDcZs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDocumentTransformersService extends Dedoc_Scramble_Tests_KernelTestDebugContainer
{
    /**
     * Gets the private 'Dedoc\Scramble\Configuration\DocumentTransformers' shared autowired service.
     *
     * @return \Dedoc\Scramble\Configuration\DocumentTransformers
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Configuration/DocumentTransformers.php';

        return $container->privates['Dedoc\\Scramble\\Configuration\\DocumentTransformers'] = new \Dedoc\Scramble\Configuration\DocumentTransformers();
    }
}
