<?php

namespace ContainerZkRDcZs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExportDocumentationService extends Dedoc_Scramble_Tests_KernelTestDebugContainer
{
    /**
     * Gets the private 'Dedoc\Scramble\Console\Commands\ExportDocumentation' shared autowired service.
     *
     * @return \Dedoc\Scramble\Console\Commands\ExportDocumentation
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Console/Commands/ExportDocumentation.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/filesystem/Filesystem.php';

        $container->privates['Dedoc\\Scramble\\Console\\Commands\\ExportDocumentation'] = $instance = new \Dedoc\Scramble\Console\Commands\ExportDocumentation(($container->privates['Dedoc\\Scramble\\Generator'] ?? $container->load('getGeneratorService')), ($container->privates['filesystem'] ??= new \Symfony\Component\Filesystem\Filesystem()), ($container->privates['Dedoc\\Scramble\\GeneratorConfig'] ?? $container->load('getGeneratorConfigService')));

        $instance->setName('scramble:export');
        $instance->setDescription('Export the OpenAPI document to a JSON file.');

        return $instance;
    }
}
