<?php

namespace ContainerZkRDcZs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGeneratorService extends Dedoc_Scramble_Tests_KernelTestDebugContainer
{
    /**
     * Gets the private 'Dedoc\Scramble\Generator' shared autowired service.
     *
     * @return \Dedoc\Scramble\Generator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Generator.php';
        include_once \dirname(__DIR__, 4).'/src/Support/OperationBuilder.php';

        return $container->privates['Dedoc\\Scramble\\Generator'] = new \Dedoc\Scramble\Generator(($container->privates['Dedoc\\Scramble\\Support\\OperationBuilder'] ??= new \Dedoc\Scramble\Support\OperationBuilder()), ($container->privates['Dedoc\\Scramble\\Infer'] ?? $container->load('getInferService')), ($container->services['router'] ?? self::getRouterService($container)), $container->parameters['scramble.config'], ($container->privates['Dedoc\\Scramble\\Support\\Generator\\TypeTransformer'] ?? $container->load('getTypeTransformerService')), new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Dedoc\\Scramble\\DocumentTransformers\\AddDocumentTags' => ['privates', 'Dedoc\\Scramble\\DocumentTransformers\\AddDocumentTags', 'getAddDocumentTagsService', true],
            'Dedoc\\Scramble\\DocumentTransformers\\CleanupUnusedResponseReferencesTransformer' => ['privates', 'Dedoc\\Scramble\\DocumentTransformers\\CleanupUnusedResponseReferencesTransformer', 'getCleanupUnusedResponseReferencesTransformerService', true],
        ], [
            'Dedoc\\Scramble\\DocumentTransformers\\AddDocumentTags' => 'Dedoc\\Scramble\\DocumentTransformers\\AddDocumentTags',
            'Dedoc\\Scramble\\DocumentTransformers\\CleanupUnusedResponseReferencesTransformer' => 'Dedoc\\Scramble\\DocumentTransformers\\CleanupUnusedResponseReferencesTransformer',
        ]));
    }
}
