<?php

namespace ContainerZkRDcZs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGeneratorConfigService extends Dedoc_Scramble_Tests_KernelTestDebugContainer
{
    /**
     * Gets the private 'Dedoc\Scramble\GeneratorConfig' shared autowired service.
     *
     * @return \Dedoc\Scramble\GeneratorConfig
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/GeneratorConfig.php';
        include_once \dirname(__DIR__, 4).'/src/Configuration/ParametersExtractors.php';
        include_once \dirname(__DIR__, 4).'/src/Configuration/OperationTransformers.php';
        include_once \dirname(__DIR__, 4).'/src/Configuration/DocumentTransformers.php';
        include_once \dirname(__DIR__, 4).'/src/Configuration/ServerVariables.php';

        return $container->privates['Dedoc\\Scramble\\GeneratorConfig'] = new \Dedoc\Scramble\GeneratorConfig([], NULL, ($container->privates['Dedoc\\Scramble\\Configuration\\ParametersExtractors'] ??= new \Dedoc\Scramble\Configuration\ParametersExtractors()), ($container->privates['Dedoc\\Scramble\\Configuration\\OperationTransformers'] ??= new \Dedoc\Scramble\Configuration\OperationTransformers()), ($container->privates['Dedoc\\Scramble\\Configuration\\DocumentTransformers'] ??= new \Dedoc\Scramble\Configuration\DocumentTransformers()), ($container->privates['Dedoc\\Scramble\\Configuration\\ServerVariables'] ??= new \Dedoc\Scramble\Configuration\ServerVariables()));
    }
}
