<?php

namespace ContainerZkRDcZs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIndexService extends Dedoc_Scramble_Tests_KernelTestDebugContainer
{
    /**
     * Gets the private 'Dedoc\Scramble\Infer\Scope\Index' shared autowired service.
     *
     * @return \Dedoc\Scramble\Infer\Scope\Index
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Infer/Contracts/Index.php';
        include_once \dirname(__DIR__, 4).'/src/Infer/Scope/Index.php';

        return $container->privates['Dedoc\\Scramble\\Infer\\Scope\\Index'] = new \Dedoc\Scramble\Infer\Scope\Index();
    }
}
