<?php

namespace ContainerZkRDcZs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInferService extends Dedoc_Scramble_Tests_KernelTestDebugContainer
{
    /**
     * Gets the private 'Dedoc\Scramble\Infer' shared autowired service.
     *
     * @return \Dedoc\Scramble\Infer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Infer.php';
        include_once \dirname(__DIR__, 4).'/src/Infer/Contracts/Index.php';
        include_once \dirname(__DIR__, 4).'/src/Infer/Scope/Index.php';
        include_once \dirname(__DIR__, 4).'/src/Configuration/InferConfig.php';

        return $container->privates['Dedoc\\Scramble\\Infer'] = new \Dedoc\Scramble\Infer(($container->privates['Dedoc\\Scramble\\Infer\\Scope\\Index'] ??= new \Dedoc\Scramble\Infer\Scope\Index()), ($container->privates['Dedoc\\Scramble\\Configuration\\InferConfig'] ??= new \Dedoc\Scramble\Configuration\InferConfig()));
    }
}
