<?php

namespace ContainerZkRDcZs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOpenApiService extends Dedoc_Scramble_Tests_KernelTestDebugContainer
{
    /**
     * Gets the private 'Dedoc\Scramble\Support\Generator\OpenApi' shared autowired service.
     *
     * @return \Dedoc\Scramble\Support\Generator\OpenApi
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Support/Generator/OpenApi.php';

        return $container->privates['Dedoc\\Scramble\\Support\\Generator\\OpenApi'] = new \Dedoc\Scramble\Support\Generator\OpenApi('3.1.0');
    }
}
