<?php

namespace ContainerZkRDcZs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOperationBuilderService extends Dedoc_Scramble_Tests_KernelTestDebugContainer
{
    /**
     * Gets the private 'Dedoc\Scramble\Support\OperationBuilder' shared autowired service.
     *
     * @return \Dedoc\Scramble\Support\OperationBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Support/OperationBuilder.php';

        return $container->privates['Dedoc\\Scramble\\Support\\OperationBuilder'] = new \Dedoc\Scramble\Support\OperationBuilder();
    }
}
