<?php

namespace ContainerZkRDcZs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypeTransformerService extends Dedoc_Scramble_Tests_KernelTestDebugContainer
{
    /**
     * Gets the private 'Dedoc\Scramble\Support\Generator\TypeTransformer' shared autowired service.
     *
     * @return \Dedoc\Scramble\Support\Generator\TypeTransformer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Support/Generator/TypeTransformer.php';

        return $container->privates['Dedoc\\Scramble\\Support\\Generator\\TypeTransformer'] = new \Dedoc\Scramble\Support\Generator\TypeTransformer(($container->privates['Dedoc\\Scramble\\Infer'] ?? $container->load('getInferService')), ($container->privates['Dedoc\\Scramble\\OpenApiContext'] ?? $container->load('getOpenApiContextService')));
    }
}
