<?php

namespace ContainerH8QtJHy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddDocumentTagsService extends Dedoc_Scramble_Tests_KernelTestDebugContainer
{
    /**
     * Gets the private 'Dedoc\Scramble\DocumentTransformers\AddDocumentTags' shared autowired service.
     *
     * @return \Dedoc\Scramble\DocumentTransformers\AddDocumentTags
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Contracts/DocumentTransformer.php';
        include_once \dirname(__DIR__, 4).'/src/DocumentTransformers/AddDocumentTags.php';

        return $container->privates['Dedoc\\Scramble\\DocumentTransformers\\AddDocumentTags'] = new \Dedoc\Scramble\DocumentTransformers\AddDocumentTags();
    }
}
