<?php

namespace ContainerH8QtJHy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDocsControllerService extends Dedoc_Scramble_Tests_KernelTestDebugContainer
{
    /**
     * Gets the public 'Dedoc\Scramble\Http\Controllers\DocsController' shared autowired service.
     *
     * @return \Dedoc\Scramble\Http\Controllers\DocsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Http/Controllers/DocsController.php';

        return $container->services['Dedoc\\Scramble\\Http\\Controllers\\DocsController'] = new \Dedoc\Scramble\Http\Controllers\DocsController(($container->privates['Dedoc\\Scramble\\Generator'] ?? $container->load('getGeneratorService')), ($container->privates['Dedoc\\Scramble\\GeneratorConfig'] ?? $container->load('getGeneratorConfigService')));
    }
}
