<?php

namespace ContainerH8QtJHy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExportDocumentation_LazyService extends Dedoc_Scramble_Tests_KernelTestDebugContainer
{
    /**
     * Gets the private '.Dedoc\Scramble\Console\Commands\ExportDocumentation.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.Dedoc\\Scramble\\Console\\Commands\\ExportDocumentation.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('scramble:export', [], 'Export the OpenAPI document to a JSON file.', false, #[\Closure(name: 'Dedoc\\Scramble\\Console\\Commands\\ExportDocumentation')] fn (): \Dedoc\Scramble\Console\Commands\ExportDocumentation => ($container->privates['Dedoc\\Scramble\\Console\\Commands\\ExportDocumentation'] ?? $container->load('getExportDocumentationService')));
    }
}
