<?php

namespace ContainerH8QtJHy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOpenApiContextService extends Dedoc_Scramble_Tests_KernelTestDebugContainer
{
    /**
     * Gets the private 'Dedoc\Scramble\OpenApiContext' shared autowired service.
     *
     * @return \Dedoc\Scramble\OpenApiContext
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/OpenApiContext.php';
        include_once \dirname(__DIR__, 4).'/src/Support/Generator/OpenApi.php';

        return $container->privates['Dedoc\\Scramble\\OpenApiContext'] = new \Dedoc\Scramble\OpenApiContext(($container->privates['Dedoc\\Scramble\\Support\\Generator\\OpenApi'] ??= new \Dedoc\Scramble\Support\Generator\OpenApi('3.1.0')), ($container->privates['Dedoc\\Scramble\\GeneratorConfig'] ?? $container->load('getGeneratorConfigService')), ($container->privates['Dedoc\\Scramble\\ContextReferences'] ?? $container->load('getContextReferencesService')));
    }
}
