<?php

namespace ContainerH8QtJHy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOperationBuilderService extends Dedoc_Scramble_Tests_KernelTestDebugContainer
{
    /**
     * Gets the private 'Dedoc\Scramble\Support\OperationBuilder' shared autowired service.
     *
     * @return \Dedoc\Scramble\Support\OperationBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Support/OperationBuilder.php';

        return $container->privates['Dedoc\\Scramble\\Support\\OperationBuilder'] = new \Dedoc\Scramble\Support\OperationBuilder(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Dedoc\\Scramble\\Support\\OperationExtensions\\DeprecationExtension' => ['privates', 'Dedoc\\Scramble\\Support\\OperationExtensions\\DeprecationExtension', 'getDeprecationExtensionService', true],
            'Dedoc\\Scramble\\Support\\OperationExtensions\\ErrorResponsesExtension' => ['privates', 'Dedoc\\Scramble\\Support\\OperationExtensions\\ErrorResponsesExtension', 'getErrorResponsesExtensionService', true],
            'Dedoc\\Scramble\\Support\\OperationExtensions\\RequestBodyExtension' => ['privates', 'Dedoc\\Scramble\\Support\\OperationExtensions\\RequestBodyExtension', 'getRequestBodyExtensionService', true],
            'Dedoc\\Scramble\\Support\\OperationExtensions\\RequestEssentialsExtension' => ['privates', 'Dedoc\\Scramble\\Support\\OperationExtensions\\RequestEssentialsExtension', 'getRequestEssentialsExtensionService', true],
            'Dedoc\\Scramble\\Support\\OperationExtensions\\ResponseExtension' => ['privates', 'Dedoc\\Scramble\\Support\\OperationExtensions\\ResponseExtension', 'getResponseExtensionService', true],
            'Dedoc\\Scramble\\Support\\OperationExtensions\\ResponseHeadersExtension' => ['privates', 'Dedoc\\Scramble\\Support\\OperationExtensions\\ResponseHeadersExtension', 'getResponseHeadersExtensionService', true],
        ], [
            'Dedoc\\Scramble\\Support\\OperationExtensions\\DeprecationExtension' => 'Dedoc\\Scramble\\Support\\OperationExtensions\\DeprecationExtension',
            'Dedoc\\Scramble\\Support\\OperationExtensions\\ErrorResponsesExtension' => 'Dedoc\\Scramble\\Support\\OperationExtensions\\ErrorResponsesExtension',
            'Dedoc\\Scramble\\Support\\OperationExtensions\\RequestBodyExtension' => 'Dedoc\\Scramble\\Support\\OperationExtensions\\RequestBodyExtension',
            'Dedoc\\Scramble\\Support\\OperationExtensions\\RequestEssentialsExtension' => 'Dedoc\\Scramble\\Support\\OperationExtensions\\RequestEssentialsExtension',
            'Dedoc\\Scramble\\Support\\OperationExtensions\\ResponseExtension' => 'Dedoc\\Scramble\\Support\\OperationExtensions\\ResponseExtension',
            'Dedoc\\Scramble\\Support\\OperationExtensions\\ResponseHeadersExtension' => 'Dedoc\\Scramble\\Support\\OperationExtensions\\ResponseHeadersExtension',
        ]));
    }
}
