<?php

namespace ContainerH8QtJHy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOperationTransformersService extends Dedoc_Scramble_Tests_KernelTestDebugContainer
{
    /**
     * Gets the private 'Dedoc\Scramble\Configuration\OperationTransformers' shared autowired service.
     *
     * @return \Dedoc\Scramble\Configuration\OperationTransformers
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Configuration/OperationTransformers.php';

        return $container->privates['Dedoc\\Scramble\\Configuration\\OperationTransformers'] = new \Dedoc\Scramble\Configuration\OperationTransformers();
    }
}
