<?php

namespace ContainerH8QtJHy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRequestBodyExtensionService extends Dedoc_Scramble_Tests_KernelTestDebugContainer
{
    /**
     * Gets the private 'Dedoc\Scramble\Support\OperationExtensions\RequestBodyExtension' shared autowired service.
     *
     * @return \Dedoc\Scramble\Support\OperationExtensions\RequestBodyExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Contracts/OperationTransformer.php';
        include_once \dirname(__DIR__, 4).'/src/Extensions/OperationExtension.php';
        include_once \dirname(__DIR__, 4).'/src/Support/OperationExtensions/RequestBodyExtension.php';

        return $container->privates['Dedoc\\Scramble\\Support\\OperationExtensions\\RequestBodyExtension'] = new \Dedoc\Scramble\Support\OperationExtensions\RequestBodyExtension(($container->privates['Dedoc\\Scramble\\Infer'] ?? $container->load('getInferService')), ($container->privates['Dedoc\\Scramble\\Support\\Generator\\TypeTransformer'] ?? $container->load('getTypeTransformerService')), ($container->privates['Dedoc\\Scramble\\GeneratorConfig'] ?? $container->load('getGeneratorConfigService')));
    }
}
