<?php

namespace ContainerH8QtJHy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRequestEssentialsExtensionService extends Dedoc_Scramble_Tests_KernelTestDebugContainer
{
    /**
     * Gets the private 'Dedoc\Scramble\Support\OperationExtensions\RequestEssentialsExtension' shared autowired service.
     *
     * @return \Dedoc\Scramble\Support\OperationExtensions\RequestEssentialsExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Contracts/OperationTransformer.php';
        include_once \dirname(__DIR__, 4).'/src/Extensions/OperationExtension.php';
        include_once \dirname(__DIR__, 4).'/src/Support/OperationExtensions/RequestEssentialsExtension.php';
        include_once \dirname(__DIR__, 4).'/src/Support/Generator/OpenApi.php';

        return $container->privates['Dedoc\\Scramble\\Support\\OperationExtensions\\RequestEssentialsExtension'] = new \Dedoc\Scramble\Support\OperationExtensions\RequestEssentialsExtension(($container->privates['Dedoc\\Scramble\\Infer'] ?? $container->load('getInferService')), ($container->privates['Dedoc\\Scramble\\Support\\Generator\\TypeTransformer'] ?? $container->load('getTypeTransformerService')), ($container->privates['Dedoc\\Scramble\\GeneratorConfig'] ?? $container->load('getGeneratorConfigService')), ($container->privates['Dedoc\\Scramble\\Support\\Generator\\OpenApi'] ??= new \Dedoc\Scramble\Support\Generator\OpenApi('3.1.0')), ($container->privates['Dedoc\\Scramble\\OpenApiContext'] ?? $container->load('getOpenApiContextService')));
    }
}
