services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Dedoc\Scramble\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Tests,Kernel.php}'
