<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH8QtJHy\Dedoc_Scramble_Tests_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH8QtJHy/Dedoc_Scramble_Tests_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerH8QtJHy.legacy');

    return;
}

if (!\class_exists(Dedoc_Scramble_Tests_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerH8QtJHy\Dedoc_Scramble_Tests_KernelTestDebugContainer::class, Dedoc_Scramble_Tests_KernelTestDebugContainer::class, false);
}

return new \ContainerH8QtJHy\Dedoc_Scramble_Tests_KernelTestDebugContainer([
    'container.build_hash' => 'H8QtJHy',
    'container.build_id' => '95c2a324',
    'container.build_time' => 1761898572,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH8QtJHy');
